# Generated by Django 4.1.3 on 2022-11-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(choices=[('SUPER RARE', 'Super Rare'), ('RARE', 'Rare'), ('UNCOMMON', 'Uncommon'), ('COMMON', 'Common')], default='COMMON', max_length=100)),
                ('pack', models.CharField(max_length=100)),
            ],
        ),
    ]
