# Generated by Django 4.1.3 on 2022-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='condition',
            field=models.CharField(choices=[('Near Mint', 'Near Mint'), ('Lightly Played', 'Lightly Played'), ('Moderately Played', 'Moderately Played'), ('Heavily Played', 'Heavily Played'), ('Damaged', 'Damaged')], default='Near Mint', max_length=100),
        ),
    ]
