# Generated by Django 4.1.3 on 2022-11-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dropoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dropoff',
            field=models.ManyToManyField(to='main_app.dropoff'),
        ),
    ]
